<a href="https://colab.research.google.com/github/lponcec94/PolyWorks/blob/main/semana_7/Ejercicio_semana_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df = pd.read_fwf('https://raw.githubusercontent.com/lponcec94/PolyWorks/main/semana_7/data/dorothea_train.txt')

In [57]:
with open('/content/drive/MyDrive/Kaggle/semana_7/dorothea_train.txt', 'r') as fr:
  file = fr.readlines()  

lista_file = [file[i].split() for i in range(len(file))]
print(lista_file[0])

lista_int_file = [[int(numero) for numero in lista] for lista in lista_file ]

print(lista_int_file[0])

df = pd.DataFrame(lista for lista in lista_int_file )

800

In [59]:
lista_file = [file[i].split() for i in range(len(file))]
print(lista_file[0])

['191', '367', '614', '634', '711', '1202', '1220', '1311', '1472', '1730', '2281', '2572', '2602', '2611', '2824', '2855', '2940', '3149', '3313', '3560', '3568', '3824', '4185', '4266', '4366', '4409', '4472', '5008', '5114', '5408', '5470', '5509', '5526', '5626', '5728', '5910', '5976', '6031', '6047', '6069', '6307', '6352', '6396', '6401', '6439', '6468', '6477', '6708', '6978', '7092', '7112', '7149', '7235', '7470', '7495', '7549', '7714', '7815', '7911', '8037', '8464', '8488', '8601', '8650', '8797', '8825', '8830', '9015', '9275', '9447', '9577', '9707', '9735', '10200', '10234', '10328', '10469', '10471', '10637', '10749', '10938', '11042', '11378', '11713', '11728', '11756', '11858', '11950', '12142', '12160', '12375', '12383', '12540', '12906', '13002', '13121', '13401', '13700', '14147', '14332', '14565', '14581', '14707', '14944', '15213', '15423', '15608', '15677', '15859', '16028', '16043', '16092', '16145', '16323', '16419', '16564', '17009', '17161', '17252', '17361', '17515', '17698', '17760', '17791', '17957', '18135', '18722', '18889', '18914', '19030', '19082', '19105', '19166', '19199', '19532', '19716', '19857', '19958', '20146', '20153', '20154', '20354', '20503', '20582', '20587', '21109', '21484', '21543', '21690', '21904', '21967', '22009', '22105', '22154', '22757', '22808', '22813', '23066', '23176', '23361', '23505', '23602', '23650', '23868', '24410', '24718', '24820', '24869', '24967', '25051', '25136', '25174', '25299', '25340', '25419', '25568', '25578', '25608', '25803', '25930', '26245', '26465', '26729', '26795', '26807', '27211', '27340', '27750', '27810', '28017', '28020', '28070', '28192', '28250', '28606', '28671', '28811', '28880', '29029', '29061', '29071', '29103', '29298', '29350', '29372', '29384', '29419', '29432', '29752', '29961', '30039', '30237', '30245', '30314', '30326', '30433', '30463', '30552', '30582', '30748', '30784', '30840', '30945', '30965', '31025', '31192', '31207', '31225', '31235', '31434', '31438', '31487', '31529', '31712', '31868', '31893', '31978', '32030', '32240', '32360', '32414', '32575', '32581', '32957', '33102', '33198', '33279', '33283', '33406', '33457', '33560', '34085', '34210', '34291', '34431', '34630', '34661', '34736', '34846', '34955', '35146', '35203', '35347', '35567', '35651', '35860', '35876', '36005', '36011', '36030', '36119', '36281', '36355', '36645', '36874', '36913', '36960', '36963', '36987', '37095', '37123', '37206', '37324', '37376', '37433', '37477', '37871', '37876', '37946', '38051', '38362', '38385', '38425', '38447', '38465', '38909', '39054', '39092', '39275', '39419', '39449', '39588', '39658', '39684', '39767', '39777', '39872', '39943', '40011', '40134', '40322', '40554', '40609', '40683', '40736', '40786', '40822', '40882', '41407', '41410', '41457', '41540', '41996', '42011', '42265', '42299', '42425', '42474', '42495', '42505', '42537', '42711', '42820', '42906', '43122', '43324', '43991', '44053', '44171', '44316', '44516', '44548', '44605', '44665', '44736', '44919', '45294', '45711', '45851', '45904', '45975', '46040', '46454', '46518', '46542', '46667', '46851', '46880', '46907', '46918', '47175', '47203', '47205', '47246', '47391', '48290', '48333', '48486', '48504', '48726', '48732', '48806', '48999', '49002', '49263', '49357', '49575', '49636', '49764', '50038', '50122', '50209', '50240', '50322', '50399', '50506', '50601', '50710', '50876', '50923', '51028', '51066', '51434', '51724', '51846', '51951', '52291', '52321', '52425', '52659', '52686', '53022', '53255', '53266', '53315', '53338', '53455', '53760', '53948', '53976', '54059', '54103', '54131', '54136', '54151', '54161', '54244', '54452', '54526', '54746', '55113', '55283', '55367', '55424', '55650', '55972', '56061', '56114', '56211', '56410', '56681', '56725', '56887', '57155', '57173', '57180', '57313', '57474', '57481', '57506', '57612', '57762', '57765', '58149', '58401', '58459', '58716', '58832', '58867', '59013', '59117', '59340', '59522', '59744', '59922', '60085', '60205', '60272', '60280', '60489', '60546', '60572', '60587', '60778', '60853', '60962', '61142', '61214', '61405', '61504', '61576', '61607', '61771', '62139', '62214', '62419', '62483', '62520', '62773', '62905', '62940', '63150', '63200', '63466', '63479', '63508', '63513', '63685', '63830', '64247', '64313', '64356', '64436', '64450', '64459', '64461', '64521', '64904', '65048', '65142', '65217', '65241', '65318', '65518', '65555', '65651', '65713', '65750', '65804', '65911', '66071', '66081', '66157', '66182', '66364', '66531', '66541', '66691', '66872', '67050', '67105', '67214', '67475', '67582', '67637', '67810', '67957', '67986', '68103', '68279', '68353', '68500', '68574', '68601', '68623', '68796', '68798', '68948', '69517', '69646', '69734', '69773', '69956', '70071', '70486', '71106', '71114', '71425', '72008', '72253', '72289', '72311', '72377', '72456', '72498', '72601', '72650', '72730', '72733', '72822', '72826', '73170', '73235', '73315', '73322', '73330', '73335', '73473', '73595', '73673', '73686', '73821', '73916', '74108', '74316', '74773', '74808', '74865', '75036', '75220', '75247', '75393', '75396', '75399', '75645', '75676', '75790', '75823', '76023', '76090', '76172', '76370', '76581', '76881', '76886', '77050', '77202', '77523', '77578', '77648', '77870', '78150', '78222', '78353', '78375', '78583', '78655', '78802', '78994', '79269', '79275', '79507', '79640', '79830', '79837', '79897', '79940', '80024', '80239', '80265', '80433', '80499', '80562', '80839', '80936', '81096', '81195', '81301', '81455', '81586', '81672', '81952', '82087', '82174', '82179', '82225', '82245', '82362', '82957', '82961', '83002', '83055', '83186', '83192', '83203', '83415', '83465', '83741', '83916', '83938', '84005', '84062', '84071', '84416', '84733', '84737', '84753', '85082', '85144', '85199', '85368', '85866', '86141', '86353', '86469', '86471', '86921', '87061', '87131', '87289', '87445', '87539', '87744', '88658', '88745', '88767', '88800', '88886', '89245', '89248', '89279', '89535', '89549', '89785', '89902', '90435', '90446', '90528', '90725', '90880', '90909', '90954', '91307', '91315', '91408', '91828', '91923', '91927', '91931', '91996', '92109', '92204', '92221', '92278', '92560', '92704', '92839', '92929', '92931', '92966', '92983', '92988', '93016', '93136', '93307', '93539', '93622', '93735', '93972', '94210', '94211', '94226', '94493', '94583', '94611', '94618', '94715', '95145', '95170', '95347', '95360', '95371', '95546', '95566', '95629', '95646', '95685', '95876', '95986', '96422', '96502', '96567', '96685', '96769', '96844', '96998', '97062', '97204', '97947', '97977', '98061', '98190', '98214', '98231', '98277', '98402', '98543', '98581', '98654', '98831', '98959', '99116', '99187', '99257', '99321', '99349', '99580', '99678', '99686', '99998']

In [37]:
lista_int_file = [[int(numero) for numero in lista] for lista in lista_file ]

In [48]:
print(lista_int_file[0])

[118, 307, 367, 478, 505, 512, 807, 878, 939, 1024, 1095, 1836, 1915, 1961, 2261, 2474, 2521, 2633, 2673, 2969, 3143, 3193, 3292, 3313, 3593, 3906, 4073, 4104, 4605, 4684, 4720, 5168, 5264, 5422, 5456, 5470, 5537, 5629, 5895, 5932, 6052, 6305, 6319, 6330, 6601, 6671, 6891, 6946, 7065, 7142, 7260, 7446, 7517, 7582, 7609, 7947, 7965, 7993, 8015, 8098, 8367, 8410, 8490, 8532, 8549, 8700, 8837, 9043, 9086, 9146, 9247, 9427, 9735, 10090, 10141, 10229, 10235, 10489, 10614, 10833, 10955, 11172, 11238, 11807, 11820, 11858, 11989, 12092, 12216, 12262, 12533, 12534, 12923, 13159, 13306, 13621, 13677, 13685, 13824, 14052, 14053, 14176, 14179, 14203, 14222, 14481, 14600, 14654, 14732, 14763, 14782, 14859, 15105, 15348, 15956, 16041, 16073, 16320, 16490, 16528, 16558, 16746, 16835, 16976, 17186, 17307, 17528, 17932, 18271, 18279, 18393, 18402, 18542, 19405, 19413, 19549, 19830, 19843, 19845, 19850, 19987, 19997, 20179, 20256, 20273, 20276, 20282, 20332, 20400, 20408, 20425, 20448, 20695, 20816, 20821, 20875, 20924, 21409, 21493, 21594, 22153, 22205, 22300, 22824, 22835, 22877, 23081, 23227, 23304, 23406, 23682, 23690, 23794, 23803, 24022, 24054, 24194, 24276, 24543, 24580, 24692, 24768, 24837, 25258, 25288, 25733, 25785, 26008, 26034, 26186, 26274, 26403, 26438, 26517, 26600, 26725, 26836, 26994, 27076, 27296, 27957, 28075, 28161, 28286, 28742, 29120, 29135, 29272, 29367, 29706, 29708, 29803, 29931, 30026, 30098, 30108, 30438, 30464, 30690, 30715, 30820, 30959, 30965, 30984, 31185, 31260, 31262, 31509, 31518, 31551, 31719, 31823, 31939, 32285, 32375, 32394, 32515, 32727, 32737, 32744, 32824, 33007, 33083, 33406, 33792, 33879, 34708, 34962, 35034, 35136, 35350, 35364, 35589, 35762, 36350, 36908, 36952, 37032, 37116, 37570, 37576, 37747, 38154, 38232, 38725, 38742, 38966, 39006, 39136, 39270, 39438, 39514, 39760, 40018, 40078, 40084, 40251, 40390, 40576, 40675, 40719, 40923, 41644, 41729, 41832, 42014, 42053, 42254, 42377, 42561, 43040, 43192, 43761, 43767, 44037, 44102, 44105, 44248, 44321, 44367, 44373, 44618, 45206, 45213, 45227, 45559, 45676, 45775, 45882, 45906, 46011, 46015, 46018, 46050, 46685, 46724, 47051, 47535, 47590, 47716, 47729, 47815, 47843, 48015, 48045, 48415, 48496, 48654, 48909, 48913, 48916, 49066, 49103, 49246, 49320, 49405, 49420, 49495, 49718, 49941, 50261, 50297, 50363, 50632, 50990, 51033, 51179, 51423, 51488, 51635, 52087, 52145, 52155, 52200, 52281, 52392, 52465, 52682, 52711, 52860, 52866, 53075, 53090, 53119, 53471, 53584, 53745, 53928, 53929, 53934, 53944, 54009, 54257, 54309, 54405, 54559, 54807, 54940, 54945, 55285, 55353, 55412, 55542, 55552, 55667, 55832, 55858, 56055, 56065, 56136, 56336, 56392, 56589, 56939, 56964, 57025, 57196, 57379, 57537, 57575, 57659, 57765, 57800, 57886, 58043, 58049, 58143, 58151, 58224, 58529, 58549, 58640, 58712, 58787, 58812, 58850, 58943, 58948, 59073, 59181, 59340, 59652, 59831, 59875, 60260, 60337, 60387, 60584, 60650, 60672, 61132, 61287, 61569, 61683, 61737, 61772, 61857, 61866, 62015, 62152, 62262, 62751, 62866, 62911, 62949, 62992, 63392, 63436, 63460, 63513, 63610, 63754, 63882, 63953, 63980, 64250, 64399, 64437, 64590, 64891, 65337, 65372, 65396, 65446, 65541, 65744, 66040, 66177, 66376, 66457, 66482, 66489, 67100, 67144, 67304, 67539, 67604, 67636, 67674, 67866, 68029, 68045, 68053, 68070, 68165, 68326, 68351, 68369, 68389, 68467, 68496, 68576, 68645, 68699, 68908, 68995, 69341, 69344, 69442, 69527, 69642, 69729, 69887, 70111, 70137, 70254, 70324, 70655, 70799, 70803, 70921, 71100, 71367, 71374, 71494, 71565, 71876, 72008, 72025, 72098, 72208, 72381, 72453, 72665, 72772, 73253, 73283, 73392, 73543, 73551, 73795, 73885, 74289, 74333, 74385, 74420, 74869, 74903, 75369, 75393, 75405, 75408, 75635, 75883, 75890, 75952, 76425, 76482, 76493, 76717, 76889, 77047, 77056, 77190, 77491, 77605, 77896, 77948, 78159, 78204, 78300, 79081, 79388, 79473, 79580, 79637, 79816, 80008, 80137, 80202, 80303, 80473, 80492, 80508, 80583, 80702, 80745, 80928, 81333, 81640, 81711, 81908, 82161, 82332, 82803, 82866, 83277, 83332, 83435, 83684, 83745, 83803, 83833, 83944, 84233, 84322, 84721, 84734, 85144, 85181, 85260, 85322, 85328, 85339, 85712, 85729, 86042, 86233, 86484, 86505, 86524, 86751, 86964, 87005, 87036, 87131, 87209, 87427, 87545, 87660, 87736, 87779, 87973, 88065, 88145, 88174, 88302, 88328, 88409, 88443, 88450, 88597, 88990, 89191, 89204, 89254, 89340, 89366, 89409, 89648, 89703, 89722, 89809, 89844, 90123, 90148, 90197, 90264, 90440, 90517, 90548, 90588, 90688, 90742, 90851, 90940, 91046, 91047, 91342, 91446, 91534, 91633, 91737, 92147, 92157, 92250, 92269, 92303, 92464, 92532, 92661, 92672, 92906, 93025, 93056, 93082, 93285, 93318, 93558, 93884, 93955, 94211, 94228, 94267, 94296, 94381, 94393, 94619, 94686, 94729, 94736, 95193, 95596, 95615, 95629, 95758, 95811, 95876, 95980, 96135, 96367, 96892, 96942, 96957, 97217, 97325, 97533, 97797, 98342, 98380, 98521, 98549, 98980, 99137, 99171, 99184, 99410, 99560, 99610, 99626, 99731, 99938]

In [77]:
for i in range(len(lista_int_file)):
  if len(lista_int_file[i]) > 6000:
    print(len(lista_int_file[i]), i)

6061 774

In [51]:
df = pd.DataFrame(lista for lista in lista_int_file )

In [52]:
df.head()

   0     1     2     3     4     5     ...  6055  6056  6057  6058  6059  6060
0   191   367   614   634   711  1202  ...   NaN   NaN   NaN   NaN   NaN   NaN
1   118   307   367   478   505   512  ...   NaN   NaN   NaN   NaN   NaN   NaN
2    10   184   284   297   320   375  ...   NaN   NaN   NaN   NaN   NaN   NaN
3    87   149   433   704   711   892  ...   NaN   NaN   NaN   NaN   NaN   NaN
4    84   118   279   316   435   505  ...   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 6061 columns]

In [69]:
df.tail()

       0     1     2     3     4     5  ...  6056  6057  6058  6059  6060  target
795  374  1031  1271  1312  1452  1517  ...   NaN   NaN   NaN   NaN   NaN      -1
796  106   465  1095  1119  1176  1658  ...   NaN   NaN   NaN   NaN   NaN      -1
797  140   273   303   354   383   436  ...   NaN   NaN   NaN   NaN   NaN      -1
798  126   150   354   377   379   702  ...   NaN   NaN   NaN   NaN   NaN      -1
799  190   191   354   412   425   433  ...   NaN   NaN   NaN   NaN   NaN       1

[5 rows x 6062 columns]

In [78]:
df.iloc[774]

0             8.0
1            19.0
2            41.0
3            67.0
4            71.0
           ...
6057      99930.0
6058      99934.0
6059      99976.0
6060      99989.0
target        1.0
Name: 774, Length: 6062, dtype: float64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Columns: 6061 entries, 0 to 6060
dtypes: float64(5404), int64(657)
memory usage: 37.0 MB

In [62]:
with open('/content/drive/MyDrive/Kaggle/semana_7/dorothea_train.labels.txt', 'r') as fr:
  file = fr.readlines()

In [64]:
print(file)

['-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '1\n', '1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '-1\n', '1\n']

In [66]:
file_clean = [int(target.strip()) for target in file]
file_clean[0]

-1

In [67]:
df['target'] = file_clean

In [68]:
df.head()

     0    1    2    3    4     5  ...  6056  6057  6058  6059  6060  target
0  191  367  614  634  711  1202  ...   NaN   NaN   NaN   NaN   NaN      -1
1  118  307  367  478  505   512  ...   NaN   NaN   NaN   NaN   NaN      -1
2   10  184  284  297  320   375  ...   NaN   NaN   NaN   NaN   NaN      -1
3   87  149  433  704  711   892  ...   NaN   NaN   NaN   NaN   NaN      -1
4   84  118  279  316  435   505  ...   NaN   NaN   NaN   NaN   NaN      -1

[5 rows x 6062 columns]